<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-newsletter-queue"><?php echo Mage::helper('newsletter')->__('Newsletter Queue') ?></h3></td>
            <td class="form-buttons">

            </td>
        </tr>
    </table>
</div>
<div>
    <?php 
		//echo $this->getChildHtml('grid') 
	?>
    
    <?php 
    	echo $this->getChildHtml('lexgrid') 
    ?>
</div>